"""Fix duplicate celular column and add new fields

Revision ID: 41c0260bd32f
Revises: cace51531a0f
Create Date: 2024-07-18 02:14:50.086634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c0260bd32f'
down_revision = 'cace51531a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Enum('primaria', 'secundaria', 'preparatoria', 'universidad'), nullable=False))
        batch_op.add_column(sa.Column('municipio', sa.Enum('saltillo', 'arteaga', 'ramos arizpe'), nullable=False))
        batch_op.add_column(sa.Column('asunto', sa.Enum('inscripcion', 'informacion', 'otros'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('asunto')
        batch_op.drop_column('municipio')
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
