"""Add new fields to Ticket model without duplicating celular

Revision ID: 8ade157f16eb
Revises: 41c0260bd32f
Create Date: 2024-07-18 02:15:28.080398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ade157f16eb'
down_revision = '41c0260bd32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Enum('primaria', 'secundaria', 'preparatoria', 'universidad', name='nivel_enum'), nullable=False, server_default='primaria'))
        batch_op.add_column(sa.Column('municipio', sa.Enum('saltillo', 'arteaga', 'ramos arizpe', name='municipio_enum'), nullable=False, server_default='saltillo'))
        batch_op.add_column(sa.Column('asunto', sa.Enum('inscripcion', 'informacion', 'otros', name='asunto_enum'), nullable=False, server_default='inscripcion'))

    # ### end Alembic commands ###

    # Remove the server default if not needed after adding the columns
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('nivel', server_default=None)
        batch_op.alter_column('municipio', server_default=None)
        batch_op.alter_column('asunto', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('asunto')
        batch_op.drop_column('municipio')
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
