"""Agregando columna qr_code a Ticket

Revision ID: 929b3b0e6516
Revises: 9bc10e7eae25
Create Date: 2024-07-17 16:04:12.446359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929b3b0e6516'
down_revision = '9bc10e7eae25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
